package org.project.es.common.module;

import org.project.es.common.module.base.BaseDictTable;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DictTable extends BaseDictTable<DictTable> {
	public static final DictTable dao = new DictTable().dao();
}

