package org.project.es.common.module;

import org.project.es.common.module.base.BaseDictData;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DictData extends BaseDictData<DictData> {
	public static final DictData dao = new DictData().dao();
}

