package org.project.es.common.module;

import org.project.es.common.module.base.BaseIndustryDetails;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class IndustryDetails extends BaseIndustryDetails<IndustryDetails> {
	public static final IndustryDetails dao = new IndustryDetails().dao();
}

