package org.project.es.common.module;

import org.project.es.common.module.base.BaseLogRecord;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class LogRecord extends BaseLogRecord<LogRecord> {
	public static final LogRecord dao = new LogRecord().dao();
}

