package org.project.es.common.module;

import org.project.es.common.module.base.BasePolicyTag;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PolicyTag extends BasePolicyTag<PolicyTag> {
	public static final PolicyTag dao = new PolicyTag().dao();
}

