package org.project.es.common.module;

import org.project.es.common.module.base.BasePolicyTagRelation;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PolicyTagRelation extends BasePolicyTagRelation<PolicyTagRelation> {
	public static final PolicyTagRelation dao = new PolicyTagRelation().dao();
}

