package org.project.es.common.module;

import org.project.es.common.module.base.BasePolicyKey;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PolicyKey extends BasePolicyKey<PolicyKey> {
	public static final PolicyKey dao = new PolicyKey().dao();
}

