package org.project.es.common.module;

import org.project.es.common.module.base.BaseSysConfig;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysConfig extends BaseSysConfig<SysConfig> {
	public static final SysConfig dao = new SysConfig().dao();
}

