package org.project.es.common.module;

import org.project.es.common.module.base.BaseTextContent;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TextContent extends BaseTextContent<TextContent> {
	public static final TextContent dao = new TextContent().dao();
}

