package org.project.es.common.module;

import org.project.es.common.module.base.BaseUserFavorites;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UserFavorites extends BaseUserFavorites<UserFavorites> {
	public static final UserFavorites dao = new UserFavorites().dao();
}

