package org.project.es.common.module;

import org.project.es.common.module.base.BaseUserFavoritesType;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UserFavoritesType extends BaseUserFavoritesType<UserFavoritesType> {
	public static final UserFavoritesType dao = new UserFavoritesType().dao();
}

