package org.project.es.common.module;

import org.project.es.common.module.base.BaseUserSearchHistory;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UserSearchHistory extends BaseUserSearchHistory<UserSearchHistory> {
	public static final UserSearchHistory dao = new UserSearchHistory().dao();
}

