package org.project.es.common.module;

import org.project.es.common.module.base.BaseUserRoleRelation;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UserRoleRelation extends BaseUserRoleRelation<UserRoleRelation> {
	public static final UserRoleRelation dao = new UserRoleRelation().dao();
}

