package org.project.es.common.module;

import org.project.es.common.module.base.BaseUserMenuRelation;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UserMenuRelation extends BaseUserMenuRelation<UserMenuRelation> {
	public static final UserMenuRelation dao = new UserMenuRelation().dao();
}

