package org.project.es.common.module.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseAgencyType<M extends BaseAgencyType<M>> extends Model<M> implements IBean {

	/**
	 * 自增主键 自增主键
	 */
	public void setId(java.math.BigInteger id) {
		set("id", id);
	}
	
	/**
	 * 自增主键 自增主键
	 */
	public java.math.BigInteger getId() {
		return get("id");
	}
	
	/**
	 * 类型名称
	 */
	public void setAgencyName(java.lang.String agencyName) {
		set("agency_name", agencyName);
	}
	
	/**
	 * 类型名称
	 */
	public java.lang.String getAgencyName() {
		return getStr("agency_name");
	}
	
	/**
	 * 机构级别 0-默认全部；1-国家级；2-省级；3-市级；4-县（县级市）；5-镇（乡）；6-街道（村）
	 */
	public void setAgencyRank(java.lang.Integer agencyRank) {
		set("agency_rank", agencyRank);
	}
	
	/**
	 * 机构级别 0-默认全部；1-国家级；2-省级；3-市级；4-县（县级市）；5-镇（乡）；6-街道（村）
	 */
	public java.lang.Integer getAgencyRank() {
		return getInt("agency_rank");
	}
	
	/**
	 * 是否删除 0-未删除；1-已删除
	 */
	public void setIsDeleted(java.lang.Integer isDeleted) {
		set("is_deleted", isDeleted);
	}
	
	/**
	 * 是否删除 0-未删除；1-已删除
	 */
	public java.lang.Integer getIsDeleted() {
		return getInt("is_deleted");
	}
	
	/**
	 * 创建时间 创建时间
	 */
	public void setCreatedTime(java.util.Date createdTime) {
		set("created_time", createdTime);
	}
	
	/**
	 * 创建时间 创建时间
	 */
	public java.util.Date getCreatedTime() {
		return getDate("created_time");
	}
	
	/**
	 * 更新时间 更新时间
	 */
	public void setUpdatedTime(java.util.Date updatedTime) {
		set("updated_time", updatedTime);
	}
	
	/**
	 * 更新时间 更新时间
	 */
	public java.util.Date getUpdatedTime() {
		return getDate("updated_time");
	}
	
}

