package org.project.es.common.module.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseLogRecord<M extends BaseLogRecord<M>> extends Model<M> implements IBean {

	/**
	 * 主键
	 */
	public void setId(java.math.BigInteger id) {
		set("id", id);
	}
	
	/**
	 * 主键
	 */
	public java.math.BigInteger getId() {
		return get("id");
	}
	
	/**
	 * 用户ID
	 */
	public void setUserId(java.math.BigInteger userId) {
		set("user_id", userId);
	}
	
	/**
	 * 用户ID
	 */
	public java.math.BigInteger getUserId() {
		return get("user_id");
	}
	
	/**
	 * 日志类型
	 */
	public void setType(java.lang.Integer type) {
		set("type", type);
	}
	
	/**
	 * 日志类型
	 */
	public java.lang.Integer getType() {
		return getInt("type");
	}
	
	/**
	 * 路由名称
	 */
	public void setControllerName(java.lang.String controllerName) {
		set("controller_name", controllerName);
	}
	
	/**
	 * 路由名称
	 */
	public java.lang.String getControllerName() {
		return getStr("controller_name");
	}
	
	/**
	 * 方法名称
	 */
	public void setActionName(java.lang.String actionName) {
		set("action_name", actionName);
	}
	
	/**
	 * 方法名称
	 */
	public java.lang.String getActionName() {
		return getStr("action_name");
	}
	
	/**
	 * 备注
	 */
	public void setDescription(java.lang.String description) {
		set("description", description);
	}
	
	/**
	 * 备注
	 */
	public java.lang.String getDescription() {
		return getStr("description");
	}
	
	/**
	 * ip地址
	 */
	public void setIpAddress(java.lang.String ipAddress) {
		set("ip_address", ipAddress);
	}
	
	/**
	 * ip地址
	 */
	public java.lang.String getIpAddress() {
		return getStr("ip_address");
	}
	
	/**
	 * 请求参数json字符串
	 */
	public void setParameterStr(java.lang.String parameterStr) {
		set("parameter_str", parameterStr);
	}
	
	/**
	 * 请求参数json字符串
	 */
	public java.lang.String getParameterStr() {
		return getStr("parameter_str");
	}
	
	/**
	 * 返回的参数集合
	 */
	public void setResult(java.lang.String result) {
		set("result", result);
	}
	
	/**
	 * 返回的参数集合
	 */
	public java.lang.String getResult() {
		return getStr("result");
	}
	
	/**
	 * 登录地址
	 */
	public void setLocation(java.lang.String location) {
		set("location", location);
	}
	
	/**
	 * 登录地址
	 */
	public java.lang.String getLocation() {
		return getStr("location");
	}
	
	/**
	 * 浏览器类型
	 */
	public void setBrowser(java.lang.String browser) {
		set("browser", browser);
	}
	
	/**
	 * 浏览器类型
	 */
	public java.lang.String getBrowser() {
		return getStr("browser");
	}
	
	/**
	 * 操作系统
	 */
	public void setOs(java.lang.String os) {
		set("os", os);
	}
	
	/**
	 * 操作系统
	 */
	public java.lang.String getOs() {
		return getStr("os");
	}
	
	/**
	 * 操作状态 1-成功 2-失败
	 */
	public void setStatus(java.lang.Integer status) {
		set("status", status);
	}
	
	/**
	 * 操作状态 1-成功 2-失败
	 */
	public java.lang.Integer getStatus() {
		return getInt("status");
	}
	
	/**
	 * 创建时间 创建时间
	 */
	public void setCreatedTime(java.util.Date createdTime) {
		set("created_time", createdTime);
	}
	
	/**
	 * 创建时间 创建时间
	 */
	public java.util.Date getCreatedTime() {
		return getDate("created_time");
	}
	
	/**
	 * 更新时间 更新时间
	 */
	public void setUpdatedTime(java.util.Date updatedTime) {
		set("updated_time", updatedTime);
	}
	
	/**
	 * 更新时间 更新时间
	 */
	public java.util.Date getUpdatedTime() {
		return getDate("updated_time");
	}
	
}

