package org.project.es.common.module.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseDictTable<M extends BaseDictTable<M>> extends Model<M> implements IBean {

	/**
	 * 主键 自增主键
	 */
	public void setId(java.math.BigInteger id) {
		set("id", id);
	}
	
	/**
	 * 主键 自增主键
	 */
	public java.math.BigInteger getId() {
		return get("id");
	}
	
	/**
	 * 名称
	 */
	public void setName(java.lang.String name) {
		set("name", name);
	}
	
	/**
	 * 名称
	 */
	public java.lang.String getName() {
		return getStr("name");
	}
	
	/**
	 * 字典标志
	 */
	public void setDictLabel(java.lang.String dictLabel) {
		set("dict_label", dictLabel);
	}
	
	/**
	 * 字典标志
	 */
	public java.lang.String getDictLabel() {
		return getStr("dict_label");
	}
	
	/**
	 * 是否启用维护 0-不启用维护 1-启用维护
	 */
	public void setIsUsed(java.lang.Integer isUsed) {
		set("is_used", isUsed);
	}
	
	/**
	 * 是否启用维护 0-不启用维护 1-启用维护
	 */
	public java.lang.Integer getIsUsed() {
		return getInt("is_used");
	}
	
	/**
	 * 排序数据 排序顺序，越小越往前
	 */
	public void setSortNumber(java.lang.Integer sortNumber) {
		set("sort_number", sortNumber);
	}
	
	/**
	 * 排序数据 排序顺序，越小越往前
	 */
	public java.lang.Integer getSortNumber() {
		return getInt("sort_number");
	}
	
	/**
	 * 是否删除 0-未删除 1-已删除
	 */
	public void setIsDeleted(java.lang.Integer isDeleted) {
		set("is_deleted", isDeleted);
	}
	
	/**
	 * 是否删除 0-未删除 1-已删除
	 */
	public java.lang.Integer getIsDeleted() {
		return getInt("is_deleted");
	}
	
	/**
	 * 创建时间 创建时间
	 */
	public void setCreatedTime(java.util.Date createdTime) {
		set("created_time", createdTime);
	}
	
	/**
	 * 创建时间 创建时间
	 */
	public java.util.Date getCreatedTime() {
		return getDate("created_time");
	}
	
	/**
	 * 更新时间 更新时间
	 */
	public void setUpdatedTime(java.util.Date updatedTime) {
		set("updated_time", updatedTime);
	}
	
	/**
	 * 更新时间 更新时间
	 */
	public java.util.Date getUpdatedTime() {
		return getDate("updated_time");
	}
	
}

