package org.project.es.common.module.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseUser<M extends BaseUser<M>> extends Model<M> implements IBean {

	/**
	 * 主键 自增主键
	 */
	public void setId(java.math.BigInteger id) {
		set("id", id);
	}
	
	/**
	 * 主键 自增主键
	 */
	public java.math.BigInteger getId() {
		return get("id");
	}
	
	/**
	 * 头像ID
	 */
	public void setPhotoFileId(java.math.BigInteger photoFileId) {
		set("photo_file_id", photoFileId);
	}
	
	/**
	 * 头像ID
	 */
	public java.math.BigInteger getPhotoFileId() {
		return get("photo_file_id");
	}
	
	/**
	 * 头像文件名称
	 */
	public void setPhotoFileName(java.lang.String photoFileName) {
		set("photo_file_name", photoFileName);
	}
	
	/**
	 * 头像文件名称
	 */
	public java.lang.String getPhotoFileName() {
		return getStr("photo_file_name");
	}
	
	/**
	 * 用户姓名
	 */
	public void setName(java.lang.String name) {
		set("name", name);
	}
	
	/**
	 * 用户姓名
	 */
	public java.lang.String getName() {
		return getStr("name");
	}
	
	/**
	 * 拼音
	 */
	public void setPinyin(java.lang.String pinyin) {
		set("pinyin", pinyin);
	}
	
	/**
	 * 拼音
	 */
	public java.lang.String getPinyin() {
		return getStr("pinyin");
	}
	
	/**
	 * 拼音索引
	 */
	public void setPinyinIndex(java.lang.String pinyinIndex) {
		set("pinyin_index", pinyinIndex);
	}
	
	/**
	 * 拼音索引
	 */
	public java.lang.String getPinyinIndex() {
		return getStr("pinyin_index");
	}
	
	/**
	 * 身份证号
	 */
	public void setIdCard(java.lang.String idCard) {
		set("id_card", idCard);
	}
	
	/**
	 * 身份证号
	 */
	public java.lang.String getIdCard() {
		return getStr("id_card");
	}
	
	/**
	 * 邮箱
	 */
	public void setEmail(java.lang.String email) {
		set("email", email);
	}
	
	/**
	 * 邮箱
	 */
	public java.lang.String getEmail() {
		return getStr("email");
	}
	
	/**
	 * 性别 0-未知 1-男 2-女
	 */
	public void setGender(java.lang.Integer gender) {
		set("gender", gender);
	}
	
	/**
	 * 性别 0-未知 1-男 2-女
	 */
	public java.lang.Integer getGender() {
		return getInt("gender");
	}
	
	/**
	 * 手机号码
	 */
	public void setMobile(java.lang.String mobile) {
		set("mobile", mobile);
	}
	
	/**
	 * 手机号码
	 */
	public java.lang.String getMobile() {
		return getStr("mobile");
	}
	
	/**
	 * 用户昵称
	 */
	public void setUserName(java.lang.String userName) {
		set("user_name", userName);
	}
	
	/**
	 * 用户昵称
	 */
	public java.lang.String getUserName() {
		return getStr("user_name");
	}
	
	/**
	 * 登录账号
	 */
	public void setAccount(java.lang.String account) {
		set("account", account);
	}
	
	/**
	 * 登录账号
	 */
	public java.lang.String getAccount() {
		return getStr("account");
	}
	
	/**
	 * 登录密码
	 */
	public void setPassword(java.lang.String password) {
		set("password", password);
	}
	
	/**
	 * 登录密码
	 */
	public java.lang.String getPassword() {
		return getStr("password");
	}
	
	/**
	 * 年龄
	 */
	public void setAge(java.lang.Integer age) {
		set("age", age);
	}
	
	/**
	 * 年龄
	 */
	public java.lang.Integer getAge() {
		return getInt("age");
	}
	
	/**
	 * 地址
	 */
	public void setAddress(java.lang.String address) {
		set("address", address);
	}
	
	/**
	 * 地址
	 */
	public java.lang.String getAddress() {
		return getStr("address");
	}
	
	/**
	 * 职业
	 */
	public void setProfession(java.lang.String profession) {
		set("profession", profession);
	}
	
	/**
	 * 职业
	 */
	public java.lang.String getProfession() {
		return getStr("profession");
	}
	
	/**
	 * 加密盐
	 */
	public void setSalt(java.lang.String salt) {
		set("salt", salt);
	}
	
	/**
	 * 加密盐
	 */
	public java.lang.String getSalt() {
		return getStr("salt");
	}
	
	/**
	 * 用户类型 1-超级管理员 2-普通用户
	 */
	public void setType(java.lang.Integer type) {
		set("type", type);
	}
	
	/**
	 * 用户类型 1-超级管理员 2-普通用户
	 */
	public java.lang.Integer getType() {
		return getInt("type");
	}
	
	/**
	 * 用户状态 1-正常 2-禁用
	 */
	public void setStatus(java.lang.Integer status) {
		set("status", status);
	}
	
	/**
	 * 用户状态 1-正常 2-禁用
	 */
	public java.lang.Integer getStatus() {
		return getInt("status");
	}
	
	/**
	 * 小程序openid
	 */
	public void setWxaOpenid(java.lang.String wxaOpenid) {
		set("wxa_openid", wxaOpenid);
	}
	
	/**
	 * 小程序openid
	 */
	public java.lang.String getWxaOpenid() {
		return getStr("wxa_openid");
	}
	
	/**
	 * 简介
	 */
	public void setInformation(java.lang.String information) {
		set("information", information);
	}
	
	/**
	 * 简介
	 */
	public java.lang.String getInformation() {
		return getStr("information");
	}
	
	/**
	 * 是否删除 0-未删除 1-已删除
	 */
	public void setIsDeleted(java.lang.Integer isDeleted) {
		set("is_deleted", isDeleted);
	}
	
	/**
	 * 是否删除 0-未删除 1-已删除
	 */
	public java.lang.Integer getIsDeleted() {
		return getInt("is_deleted");
	}
	
	/**
	 * 创建时间 创建时间
	 */
	public void setCreatedTime(java.util.Date createdTime) {
		set("created_time", createdTime);
	}
	
	/**
	 * 创建时间 创建时间
	 */
	public java.util.Date getCreatedTime() {
		return getDate("created_time");
	}
	
	/**
	 * 更新时间 更新时间
	 */
	public void setUpdatedTime(java.util.Date updatedTime) {
		set("updated_time", updatedTime);
	}
	
	/**
	 * 更新时间 更新时间
	 */
	public java.util.Date getUpdatedTime() {
		return getDate("updated_time");
	}
	
}

