package org.project.es.common.module.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseMessage<M extends BaseMessage<M>> extends Model<M> implements IBean {

	/**
	 * 自增主键 自增主键
	 */
	public void setId(java.math.BigInteger id) {
		set("id", id);
	}
	
	/**
	 * 自增主键 自增主键
	 */
	public java.math.BigInteger getId() {
		return get("id");
	}
	
	/**
	 * 用户标识号
	 */
	public void setUserId(java.math.BigInteger userId) {
		set("user_id", userId);
	}
	
	/**
	 * 用户标识号
	 */
	public java.math.BigInteger getUserId() {
		return get("user_id");
	}
	
	/**
	 * 消息标题
	 */
	public void setTitle(java.lang.String title) {
		set("title", title);
	}
	
	/**
	 * 消息标题
	 */
	public java.lang.String getTitle() {
		return getStr("title");
	}
	
	/**
	 * 消息内容标识号
	 */
	public void setTextContentId(java.math.BigInteger textContentId) {
		set("text_content_id", textContentId);
	}
	
	/**
	 * 消息内容标识号
	 */
	public java.math.BigInteger getTextContentId() {
		return get("text_content_id");
	}
	
	/**
	 * 面向群体类型 0-全部；1；2；3
	 */
	public void setType(java.lang.Integer type) {
		set("type", type);
	}
	
	/**
	 * 面向群体类型 0-全部；1；2；3
	 */
	public java.lang.Integer getType() {
		return getInt("type");
	}
	
	/**
	 * 定时发送时间
	 */
	public void setTime(java.util.Date time) {
		set("time", time);
	}
	
	/**
	 * 定时发送时间
	 */
	public java.util.Date getTime() {
		return getDate("time");
	}
	
	/**
	 * 是否删除 0-未删除；1-已删除
	 */
	public void setIsDeleted(java.lang.Integer isDeleted) {
		set("is_deleted", isDeleted);
	}
	
	/**
	 * 是否删除 0-未删除；1-已删除
	 */
	public java.lang.Integer getIsDeleted() {
		return getInt("is_deleted");
	}
	
	/**
	 * 创建时间 创建时间
	 */
	public void setCreatedTime(java.util.Date createdTime) {
		set("created_time", createdTime);
	}
	
	/**
	 * 创建时间 创建时间
	 */
	public java.util.Date getCreatedTime() {
		return getDate("created_time");
	}
	
	/**
	 * 更新时间 更新时间
	 */
	public void setUpdatedTime(java.util.Date updatedTime) {
		set("updated_time", updatedTime);
	}
	
	/**
	 * 更新时间 更新时间
	 */
	public java.util.Date getUpdatedTime() {
		return getDate("updated_time");
	}
	
}

