package org.project.es.common.module;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {
	
	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("agency_type", "id", AgencyType.class);
		arp.addMapping("dict_data", "id", DictData.class);
		arp.addMapping("dict_table", "id", DictTable.class);
		arp.addMapping("file", "id", File.class);
		arp.addMapping("industry", "id", Industry.class);
		arp.addMapping("industry_details", "id", IndustryDetails.class);
		arp.addMapping("log_record", "id", LogRecord.class);
		arp.addMapping("login_info", "id", LoginInfo.class);
		arp.addMapping("menu", "id", Menu.class);
		arp.addMapping("message", "id", Message.class);
		arp.addMapping("message_file", "id", MessageFile.class);
		arp.addMapping("policy", "id", Policy.class);
		arp.addMapping("policy_agency_relation", "id", PolicyAgencyRelation.class);
		arp.addMapping("policy_key", "id", PolicyKey.class);
		arp.addMapping("policy_relation", "id", PolicyRelation.class);
		arp.addMapping("policy_tag", "id", PolicyTag.class);
		arp.addMapping("policy_tag_relation", "id", PolicyTagRelation.class);
		arp.addMapping("role", "id", Role.class);
		arp.addMapping("role_menu_relation", "id", RoleMenuRelation.class);
		arp.addMapping("sys_config", "id", SysConfig.class);
		arp.addMapping("text_content", "id", TextContent.class);
		arp.addMapping("user", "id", User.class);
		arp.addMapping("user_browse_history", "id", UserBrowseHistory.class);
		arp.addMapping("user_favorites", "id", UserFavorites.class);
		arp.addMapping("user_favorites_type", "id", UserFavoritesType.class);
		arp.addMapping("user_menu_relation", "id", UserMenuRelation.class);
		arp.addMapping("user_policy_content_relation", "id", UserPolicyContentRelation.class);
		arp.addMapping("user_role_relation", "id", UserRoleRelation.class);
		arp.addMapping("user_search_history", "id", UserSearchHistory.class);
		arp.addMapping("user_session", "id", UserSession.class);
	}
}


