package org.project.es.common.module;

import org.project.es.common.module.base.BaseAgencyType;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AgencyType extends BaseAgencyType<AgencyType> {
	public static final AgencyType dao = new AgencyType().dao();
}

