package org.project.es.common.module;

import org.project.es.common.module.base.BaseIndustry;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Industry extends BaseIndustry<Industry> {
	public static final Industry dao = new Industry().dao();
}

