package org.project.es.common.module;

import org.project.es.common.module.base.BaseMessageFile;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class MessageFile extends BaseMessageFile<MessageFile> {
	public static final MessageFile dao = new MessageFile().dao();
}

