package org.project.es.common.module;

import org.project.es.common.module.base.BasePolicyAgencyRelation;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PolicyAgencyRelation extends BasePolicyAgencyRelation<PolicyAgencyRelation> {
	public static final PolicyAgencyRelation dao = new PolicyAgencyRelation().dao();
}

