package org.project.es.common.module;

import org.project.es.common.module.base.BasePolicyRelation;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PolicyRelation extends BasePolicyRelation<PolicyRelation> {
	public static final PolicyRelation dao = new PolicyRelation().dao();
}

