package org.project.es.common.module;

import org.project.es.common.module.base.BasePolicy;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Policy extends BasePolicy<Policy> {
	public static final Policy dao = new Policy().dao();
}

