package org.project.es.common.module;

import org.project.es.common.module.base.BaseRoleMenuRelation;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class RoleMenuRelation extends BaseRoleMenuRelation<RoleMenuRelation> {
	public static final RoleMenuRelation dao = new RoleMenuRelation().dao();
}

