package org.project.es.common.module;

import org.project.es.common.module.base.BaseUserPolicyContentRelation;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UserPolicyContentRelation extends BaseUserPolicyContentRelation<UserPolicyContentRelation> {
	public static final UserPolicyContentRelation dao = new UserPolicyContentRelation().dao();
}

