package org.project.es.common.module;

import org.project.es.common.module.base.BaseUserBrowseHistory;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UserBrowseHistory extends BaseUserBrowseHistory<UserBrowseHistory> {
	public static final UserBrowseHistory dao = new UserBrowseHistory().dao();
}

