package org.project.es.common.module.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BasePolicy<M extends BasePolicy<M>> extends Model<M> implements IBean {

	/**
	 * 自增主键;自增主键
	 */
	public void setId(java.math.BigInteger id) {
		set("id", id);
	}
	
	/**
	 * 自增主键;自增主键
	 */
	public java.math.BigInteger getId() {
		return get("id");
	}
	
	/**
	 * 政策标题
	 */
	public void setPolicyTitle(java.lang.String policyTitle) {
		set("policy_title", policyTitle);
	}
	
	/**
	 * 政策标题
	 */
	public java.lang.String getPolicyTitle() {
		return getStr("policy_title");
	}
	
	/**
	 * 级别
	 */
	public void setPolicyGrade(java.lang.String policyGrade) {
		set("policy_grade", policyGrade);
	}
	
	/**
	 * 级别
	 */
	public java.lang.String getPolicyGrade() {
		return getStr("policy_grade");
	}
	
	/**
	 * 发布机构-id
	 */
	public void setPubAgencyId(java.lang.String pubAgencyId) {
		set("pub_agency_id", pubAgencyId);
	}
	
	/**
	 * 发布机构-id
	 */
	public java.lang.String getPubAgencyId() {
		return getStr("pub_agency_id");
	}
	
	/**
	 * 发布机构标准名称
	 */
	public void setPubAgencyFullname(java.lang.String pubAgencyFullname) {
		set("pub_agency_fullname", pubAgencyFullname);
	}
	
	/**
	 * 发布机构标准名称
	 */
	public java.lang.String getPubAgencyFullname() {
		return getStr("pub_agency_fullname");
	}
	
	/**
	 * 发文字号
	 */
	public void setPubNumber(java.lang.String pubNumber) {
		set("pub_number", pubNumber);
	}
	
	/**
	 * 发文字号
	 */
	public java.lang.String getPubNumber() {
		return getStr("pub_number");
	}
	
	/**
	 * 发布时间
	 */
	public void setPubTime(java.lang.String pubTime) {
		set("pub_time", pubTime);
	}
	
	/**
	 * 发布时间
	 */
	public java.lang.String getPubTime() {
		return getStr("pub_time");
	}
	
	/**
	 * 政策种类
	 */
	public void setPolicyType(java.lang.String policyType) {
		set("policy_type", policyType);
	}
	
	/**
	 * 政策种类
	 */
	public java.lang.String getPolicyType() {
		return getStr("policy_type");
	}
	
	/**
	 * 正文内容标识;es的检索与mysql无关，直接存内容
	 */
	public void setTextContent(java.lang.String textContent) {
		set("text_content", textContent);
	}
	
	/**
	 * 正文内容标识;es的检索与mysql无关，直接存内容
	 */
	public java.lang.String getTextContent() {
		return getStr("text_content");
	}
	
	/**
	 * 省份
	 */
	public void setProvince(java.lang.String province) {
		set("province", province);
	}
	
	/**
	 * 省份
	 */
	public java.lang.String getProvince() {
		return getStr("province");
	}
	
	/**
	 * 地市
	 */
	public void setCity(java.lang.String city) {
		set("city", city);
	}
	
	/**
	 * 地市
	 */
	public java.lang.String getCity() {
		return getStr("city");
	}
	
	/**
	 * 来源
	 */
	public void setPolicySource(java.lang.String policySource) {
		set("policy_source", policySource);
	}
	
	/**
	 * 来源
	 */
	public java.lang.String getPolicySource() {
		return getStr("policy_source");
	}
	
	/**
	 * 附件标识号
	 */
	public void setFileId(java.math.BigInteger fileId) {
		set("file_id", fileId);
	}
	
	/**
	 * 附件标识号
	 */
	public java.math.BigInteger getFileId() {
		return get("file_id");
	}
	
	/**
	 * 浏览量
	 */
	public void setViews(java.lang.Long views) {
		set("views", views);
	}
	
	/**
	 * 浏览量
	 */
	public java.lang.Long getViews() {
		return getLong("views");
	}
	
	/**
	 * 发布状态;1-待发布；2-已发布
	 */
	public void setPubStatus(java.lang.Integer pubStatus) {
		set("pub_status", pubStatus);
	}
	
	/**
	 * 发布状态;1-待发布；2-已发布
	 */
	public java.lang.Integer getPubStatus() {
		return getInt("pub_status");
	}
	
	/**
	 * 是否被爬取;0-非爬取；1-被爬取
	 */
	public void setIsCrawled(java.lang.Integer isCrawled) {
		set("is_crawled", isCrawled);
	}
	
	/**
	 * 是否被爬取;0-非爬取；1-被爬取
	 */
	public java.lang.Integer getIsCrawled() {
		return getInt("is_crawled");
	}
	
	/**
	 * 来源URL;如果是爬取，记录url
	 */
	public void setUrl(java.lang.String url) {
		set("url", url);
	}
	
	/**
	 * 来源URL;如果是爬取，记录url
	 */
	public java.lang.String getUrl() {
		return getStr("url");
	}
	
	/**
	 * 是否删除;0-未删除；1-已删除
	 */
	public void setIsDeleted(java.lang.Integer isDeleted) {
		set("is_deleted", isDeleted);
	}
	
	/**
	 * 是否删除;0-未删除；1-已删除
	 */
	public java.lang.Integer getIsDeleted() {
		return getInt("is_deleted");
	}
	
	/**
	 * 创建时间;创建时间
	 */
	public void setCreatedTime(java.util.Date createdTime) {
		set("created_time", createdTime);
	}
	
	/**
	 * 创建时间;创建时间
	 */
	public java.util.Date getCreatedTime() {
		return getDate("created_time");
	}
	
	/**
	 * 更新时间;更新时间
	 */
	public void setUpdatedTime(java.util.Date updatedTime) {
		set("updated_time", updatedTime);
	}
	
	/**
	 * 更新时间;更新时间
	 */
	public java.util.Date getUpdatedTime() {
		return getDate("updated_time");
	}
	
	/**
	 * 所属分类
	 */
	public void setLabel(java.lang.String label) {
		set("label", label);
	}
	
	/**
	 * 所属分类
	 */
	public java.lang.String getLabel() {
		return getStr("label");
	}
	
	/**
	 * 分类id
	 */
	public void setLabelNum(java.lang.Integer labelNum) {
		set("label_num", labelNum);
	}
	
	/**
	 * 分类id
	 */
	public java.lang.Integer getLabelNum() {
		return getInt("label_num");
	}
	
	public void setProvinceNum(java.lang.Integer provinceNum) {
		set("province_num", provinceNum);
	}
	
	public java.lang.Integer getProvinceNum() {
		return getInt("province_num");
	}
	
	public void setPolicyId(java.lang.Long policyId) {
		set("policy_id", policyId);
	}
	
	public java.lang.Long getPolicyId() {
		return getLong("policy_id");
	}
	
}

