package org.project.es.common.module.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseDictData<M extends BaseDictData<M>> extends Model<M> implements IBean {

	/**
	 * 主键 自增主键
	 */
	public void setId(java.math.BigInteger id) {
		set("id", id);
	}
	
	/**
	 * 主键 自增主键
	 */
	public java.math.BigInteger getId() {
		return get("id");
	}
	
	/**
	 * 对应字典标志
	 */
	public void setDictLabel(java.lang.String dictLabel) {
		set("dict_label", dictLabel);
	}
	
	/**
	 * 对应字典标志
	 */
	public java.lang.String getDictLabel() {
		return getStr("dict_label");
	}
	
	/**
	 * 名称
	 */
	public void setName(java.lang.String name) {
		set("name", name);
	}
	
	/**
	 * 名称
	 */
	public java.lang.String getName() {
		return getStr("name");
	}
	
	/**
	 * 状态 1-正常 2-禁用
	 */
	public void setStatus(java.lang.Integer status) {
		set("status", status);
	}
	
	/**
	 * 状态 1-正常 2-禁用
	 */
	public java.lang.Integer getStatus() {
		return getInt("status");
	}
	
	/**
	 * 排序数字 值越小越靠前
	 */
	public void setSortNumber(java.lang.Integer sortNumber) {
		set("sort_number", sortNumber);
	}
	
	/**
	 * 排序数字 值越小越靠前
	 */
	public java.lang.Integer getSortNumber() {
		return getInt("sort_number");
	}
	
	/**
	 * 备注
	 */
	public void setRemark(java.lang.String remark) {
		set("remark", remark);
	}
	
	/**
	 * 备注
	 */
	public java.lang.String getRemark() {
		return getStr("remark");
	}
	
	/**
	 * 是否删除 0-未删除 1-已删除
	 */
	public void setIsDeleted(java.lang.Integer isDeleted) {
		set("is_deleted", isDeleted);
	}
	
	/**
	 * 是否删除 0-未删除 1-已删除
	 */
	public java.lang.Integer getIsDeleted() {
		return getInt("is_deleted");
	}
	
	/**
	 * 创建时间 创建时间
	 */
	public void setCreatedTime(java.util.Date createdTime) {
		set("created_time", createdTime);
	}
	
	/**
	 * 创建时间 创建时间
	 */
	public java.util.Date getCreatedTime() {
		return getDate("created_time");
	}
	
	/**
	 * 更新时间 更新时间
	 */
	public void setUpdatedTime(java.util.Date updatedTime) {
		set("updated_time", updatedTime);
	}
	
	/**
	 * 更新时间 更新时间
	 */
	public java.util.Date getUpdatedTime() {
		return getDate("updated_time");
	}
	
}

