package org.project.es.common.module.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BasePolicyTagRelation<M extends BasePolicyTagRelation<M>> extends Model<M> implements IBean {

	/**
	 * 自增主键 自增主键
	 */
	public void setId(java.math.BigInteger id) {
		set("id", id);
	}
	
	/**
	 * 自增主键 自增主键
	 */
	public java.math.BigInteger getId() {
		return get("id");
	}
	
	/**
	 * 政策标识号
	 */
	public void setPolicyId(java.math.BigInteger policyId) {
		set("policy_id", policyId);
	}
	
	/**
	 * 政策标识号
	 */
	public java.math.BigInteger getPolicyId() {
		return get("policy_id");
	}
	
	/**
	 * 标签标识号
	 */
	public void setPolicyTagId(java.math.BigInteger policyTagId) {
		set("policy_tag_id", policyTagId);
	}
	
	/**
	 * 标签标识号
	 */
	public java.math.BigInteger getPolicyTagId() {
		return get("policy_tag_id");
	}
	
	/**
	 * 行业细分类别标识号
	 */
	public void setIndustryDetailsId(java.math.BigInteger industryDetailsId) {
		set("industry_details_id", industryDetailsId);
	}
	
	/**
	 * 行业细分类别标识号
	 */
	public java.math.BigInteger getIndustryDetailsId() {
		return get("industry_details_id");
	}
	
	/**
	 * 是否删除 0-未删除；1-已删除
	 */
	public void setIsDeleted(java.lang.Integer isDeleted) {
		set("is_deleted", isDeleted);
	}
	
	/**
	 * 是否删除 0-未删除；1-已删除
	 */
	public java.lang.Integer getIsDeleted() {
		return getInt("is_deleted");
	}
	
	/**
	 * 创建时间 创建时间
	 */
	public void setCreatedTime(java.util.Date createdTime) {
		set("created_time", createdTime);
	}
	
	/**
	 * 创建时间 创建时间
	 */
	public java.util.Date getCreatedTime() {
		return getDate("created_time");
	}
	
	/**
	 * 更新时间 更新时间
	 */
	public void setUpdatedTime(java.util.Date updatedTime) {
		set("updated_time", updatedTime);
	}
	
	/**
	 * 更新时间 更新时间
	 */
	public java.util.Date getUpdatedTime() {
		return getDate("updated_time");
	}
	
}

