package org.project.es.common.module.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseMenu<M extends BaseMenu<M>> extends Model<M> implements IBean {

	/**
	 * 主键 自增主键
	 */
	public void setId(java.math.BigInteger id) {
		set("id", id);
	}
	
	/**
	 * 主键 自增主键
	 */
	public java.math.BigInteger getId() {
		return get("id");
	}
	
	/**
	 * 名称
	 */
	public void setName(java.lang.String name) {
		set("name", name);
	}
	
	/**
	 * 名称
	 */
	public java.lang.String getName() {
		return getStr("name");
	}
	
	/**
	 * 标题
	 */
	public void setTitle(java.lang.String title) {
		set("title", title);
	}
	
	/**
	 * 标题
	 */
	public java.lang.String getTitle() {
		return getStr("title");
	}
	
	/**
	 * 图标
	 */
	public void setIcon(java.lang.String icon) {
		set("icon", icon);
	}
	
	/**
	 * 图标
	 */
	public java.lang.String getIcon() {
		return getStr("icon");
	}
	
	/**
	 * 父节点ID 如果存在父节点，则对应父节点id
	 */
	public void setParentId(java.math.BigInteger parentId) {
		set("parent_id", parentId);
	}
	
	/**
	 * 父节点ID 如果存在父节点，则对应父节点id
	 */
	public java.math.BigInteger getParentId() {
		return get("parent_id");
	}
	
	/**
	 * 父节点ID集合 该节点的所有父节点集合，从根节点一直到当前节点的直接父节点，父节点直接以,分隔
	 */
	public void setParentIdList(java.lang.String parentIdList) {
		set("parent_id_list", parentIdList);
	}
	
	/**
	 * 父节点ID集合 该节点的所有父节点集合，从根节点一直到当前节点的直接父节点，父节点直接以,分隔
	 */
	public java.lang.String getParentIdList() {
		return getStr("parent_id_list");
	}
	
	/**
	 * 当前节点是否为父节点 0-否 1-是
	 */
	public void setIsParent(java.lang.Integer isParent) {
		set("is_parent", isParent);
	}
	
	/**
	 * 当前节点是否为父节点 0-否 1-是
	 */
	public java.lang.Integer getIsParent() {
		return getInt("is_parent");
	}
	
	/**
	 * 层级 根节点为第一层级
	 */
	public void setLevel(java.lang.Integer level) {
		set("level", level);
	}
	
	/**
	 * 层级 根节点为第一层级
	 */
	public java.lang.Integer getLevel() {
		return getInt("level");
	}
	
	/**
	 * 排序值 值越小越靠前
	 */
	public void setOrderNumber(java.lang.Integer orderNumber) {
		set("order_number", orderNumber);
	}
	
	/**
	 * 排序值 值越小越靠前
	 */
	public java.lang.Integer getOrderNumber() {
		return getInt("order_number");
	}
	
	/**
	 * 页面路径
	 */
	public void setPath(java.lang.String path) {
		set("path", path);
	}
	
	/**
	 * 页面路径
	 */
	public java.lang.String getPath() {
		return getStr("path");
	}
	
	/**
	 * 组件路径
	 */
	public void setComponentPath(java.lang.String componentPath) {
		set("component_path", componentPath);
	}
	
	/**
	 * 组件路径
	 */
	public java.lang.String getComponentPath() {
		return getStr("component_path");
	}
	
	/**
	 * 权限标识
	 */
	public void setPermissionStr(java.lang.String permissionStr) {
		set("permission_str", permissionStr);
	}
	
	/**
	 * 权限标识
	 */
	public java.lang.String getPermissionStr() {
		return getStr("permission_str");
	}
	
	/**
	 * 重定向地址 面包屑点击事件
	 */
	public void setRedirectPath(java.lang.String redirectPath) {
		set("redirect_path", redirectPath);
	}
	
	/**
	 * 重定向地址 面包屑点击事件
	 */
	public java.lang.String getRedirectPath() {
		return getStr("redirect_path");
	}
	
	/**
	 * 类型 1-菜单 2-按钮
	 */
	public void setType(java.lang.Integer type) {
		set("type", type);
	}
	
	/**
	 * 类型 1-菜单 2-按钮
	 */
	public java.lang.Integer getType() {
		return getInt("type");
	}
	
	/**
	 * 状态 1-正常 2-禁用
	 */
	public void setStatus(java.lang.Integer status) {
		set("status", status);
	}
	
	/**
	 * 状态 1-正常 2-禁用
	 */
	public java.lang.Integer getStatus() {
		return getInt("status");
	}
	
	/**
	 * 是否显示 0-不显示 1-显示
	 */
	public void setIsShow(java.lang.Integer isShow) {
		set("is_show", isShow);
	}
	
	/**
	 * 是否显示 0-不显示 1-显示
	 */
	public java.lang.Integer getIsShow() {
		return getInt("is_show");
	}
	
	/**
	 * 是否一直显示 0-否 1-是
设置为1，表示菜单会一直在根目录显示
	 */
	public void setAlwaysShow(java.lang.Integer alwaysShow) {
		set("always_show", alwaysShow);
	}
	
	/**
	 * 是否一直显示 0-否 1-是
设置为1，表示菜单会一直在根目录显示
	 */
	public java.lang.Integer getAlwaysShow() {
		return getInt("always_show");
	}
	
	/**
	 * 是否不缓存 0-缓存 1-不缓存
	 */
	public void setNoCache(java.lang.Integer noCache) {
		set("no_cache", noCache);
	}
	
	/**
	 * 是否不缓存 0-缓存 1-不缓存
	 */
	public java.lang.Integer getNoCache() {
		return getInt("no_cache");
	}
	
	/**
	 * 是否缓存 0-不缓存 1-缓存
	 */
	public void setKeepAlive(java.lang.Integer keepAlive) {
		set("keep_alive", keepAlive);
	}
	
	/**
	 * 是否缓存 0-不缓存 1-缓存
	 */
	public java.lang.Integer getKeepAlive() {
		return getInt("keep_alive");
	}
	
	/**
	 * 是否固定在标签页 0-否 1-是
	 */
	public void setAffix(java.lang.Integer affix) {
		set("affix", affix);
	}
	
	/**
	 * 是否固定在标签页 0-否 1-是
	 */
	public java.lang.Integer getAffix() {
		return getInt("affix");
	}
	
	/**
	 * 是否显示面包屑 0-不显示 1-显示
	 */
	public void setBreadcrumb(java.lang.Integer breadcrumb) {
		set("breadcrumb", breadcrumb);
	}
	
	/**
	 * 是否显示面包屑 0-不显示 1-显示
	 */
	public java.lang.Integer getBreadcrumb() {
		return getInt("breadcrumb");
	}
	
	/**
	 * 激活对应的菜单 如果设置了，则以对应的显示菜单名为准
	 */
	public void setActiveMenu(java.lang.String activeMenu) {
		set("active_menu", activeMenu);
	}
	
	/**
	 * 激活对应的菜单 如果设置了，则以对应的显示菜单名为准
	 */
	public java.lang.String getActiveMenu() {
		return getStr("active_menu");
	}
	
	/**
	 * 是否删除 0-未删除 1-已删除
	 */
	public void setIsDeleted(java.lang.Integer isDeleted) {
		set("is_deleted", isDeleted);
	}
	
	/**
	 * 是否删除 0-未删除 1-已删除
	 */
	public java.lang.Integer getIsDeleted() {
		return getInt("is_deleted");
	}
	
	/**
	 * 创建时间 创建时间
	 */
	public void setCreatedTime(java.util.Date createdTime) {
		set("created_time", createdTime);
	}
	
	/**
	 * 创建时间 创建时间
	 */
	public java.util.Date getCreatedTime() {
		return getDate("created_time");
	}
	
	/**
	 * 更新时间 更新时间
	 */
	public void setUpdatedTime(java.util.Date updatedTime) {
		set("updated_time", updatedTime);
	}
	
	/**
	 * 更新时间 更新时间
	 */
	public java.util.Date getUpdatedTime() {
		return getDate("updated_time");
	}
	
}

